---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-discord-bot
  namespace: project-discord-bot
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: project-discord-bot
      containers:
      - image: devlaunchers/project_discord-bot:sha-0bca583
        name: project-discord-bot
