apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-discord-bot-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi